<?php
return [
    'app' => [
        'env' => $_ENV['APP_ENV'] ?? 'local',
        'debug' => filter_var($_ENV['APP_DEBUG'] ?? false, FILTER_VALIDATE_BOOL),
        'url' => $_ENV['APP_URL'] ?? 'http://localhost',
        'key' => $_ENV['APP_KEY'] ?? '',
        'force_https' => filter_var($_ENV['FORCE_HTTPS'] ?? false, FILTER_VALIDATE_BOOL),
        'trusted_hosts' => array_filter(array_map('trim', explode(',', $_ENV['TRUSTED_HOSTS'] ?? 'localhost'))),
        // X-Forwarded-* headers are trusted only when REMOTE_ADDR is in this list.
        'trusted_proxies' => array_filter(array_map('trim', explode(',', $_ENV['TRUSTED_PROXIES'] ?? ''))),
    ],

    'secrets' => [
        'enabled' => filter_var($_ENV['SECRETS_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'provider' => [
            // env, array. Cloud/Vault providers can implement SecretProviderInterface later.
            'driver' => $_ENV['SECRETS_DRIVER'] ?? 'env',
            'prefix' => $_ENV['SECRETS_PREFIX'] ?? '',
        ],
        'redaction' => [
            'enabled' => filter_var($_ENV['SECRETS_REDACTION_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
            'replacement' => $_ENV['SECRETS_REDACTION_REPLACEMENT'] ?? '[redacted]',
            'show_last' => (int)($_ENV['SECRETS_REDACTION_SHOW_LAST'] ?? 0),
            'redact_config_dumps' => true,
            'redact_audit_metadata' => true,
            'redact_error_context' => true,
        ],
        'derivation' => [
            'enabled' => filter_var($_ENV['SECRETS_DERIVATION_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
            'master' => $_ENV['SECRETS_DERIVATION_MASTER'] ?? 'APP_KEY',
            'salt' => $_ENV['APP_SECRET_SALT'] ?? 'mnb-secure-core',
        ],
        'definitions' => [
            'app.key' => [
                'env' => 'APP_KEY',
                'required' => true,
                'production_required' => true,
                'min_length' => 32,
                'purpose' => 'master application key',
                'rotatable' => true,
                'current_key_id' => $_ENV['APP_KEY_ID'] ?? 'app-v1',
                'created_at' => $_ENV['APP_KEY_CREATED_AT'] ?? null,
            ],
            'data.key' => [
                'env' => 'DATA_KEY',
                'required' => false,
                'derive_from' => 'app.key',
                'min_length' => 32,
                'purpose' => 'data encryption',
                'rotatable' => true,
                'current_key_id' => $_ENV['DATA_KEY_ID'] ?? 'data-v1',
                'created_at' => $_ENV['DATA_KEY_CREATED_AT'] ?? null,
            ],
            'data.search_hash_key' => [
                'env' => 'DATA_SEARCH_HASH_KEY',
                'required' => false,
                'derive_from' => 'app.key',
                'min_length' => 32,
                'purpose' => 'search hash / blind indexes',
                'rotatable' => true,
            ],
            'signed_url.key' => [
                'env' => 'SIGNED_URL_KEY',
                'required' => false,
                'derive_from' => 'app.key',
                'min_length' => 32,
                'purpose' => 'signed URL HMAC',
                'rotatable' => true,
            ],
            'webhook.secret' => [
                'env' => 'WEBHOOK_SECRET',
                'required' => false,
                'production_required' => false,
                'min_length' => 32,
                'purpose' => 'webhook HMAC verification',
                'rotatable' => true,
            ],
            'cache.encryption_key' => [
                'env' => 'CACHE_ENCRYPTION_KEY',
                'required' => false,
                'derive_from' => 'app.key',
                'min_length' => 32,
                'purpose' => 'sensitive cache encryption',
                'rotatable' => true,
            ],
            'backup.encryption_key' => [
                'env' => 'BACKUP_ENCRYPTION_KEY',
                'required' => false,
                'derive_from' => 'app.key',
                'min_length' => 32,
                'purpose' => 'backup encryption/signing',
                'rotatable' => true,
            ],
        ],
        'rotation' => [
            'warn_after_days' => (int)($_ENV['SECRETS_ROTATION_WARN_AFTER_DAYS'] ?? 180),
            'fail_after_days' => (int)($_ENV['SECRETS_ROTATION_FAIL_AFTER_DAYS'] ?? 365),
        ],
        'scanning' => [
            'enabled' => filter_var($_ENV['SECRETS_SCAN_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
            'entropy' => filter_var($_ENV['SECRETS_SCAN_ENTROPY'] ?? true, FILTER_VALIDATE_BOOL),
            'fail_on' => $_ENV['SECRETS_SCAN_FAIL_ON'] ?? 'high',
            'ignore_paths' => ['vendor/', 'storage/', '.git/', 'node_modules/'],
            'allow_patterns' => ['change-me', 'example', 'test-key', 'your-'],
        ],
    ],

    'cookies' => [
        'secure' => filter_var($_ENV['SESSION_SECURE'] ?? false, FILTER_VALIDATE_BOOL),
        'http_only' => filter_var($_ENV['SESSION_HTTP_ONLY'] ?? true, FILTER_VALIDATE_BOOL),
        'same_site' => $_ENV['SESSION_SAME_SITE'] ?? 'Lax',
    ],
    'paths' => [
        'private_storage' => $_ENV['STORAGE_PRIVATE_PATH'] ?? __DIR__ . '/../storage/private',
        'quarantine' => $_ENV['STORAGE_QUARANTINE_PATH'] ?? __DIR__ . '/../storage/quarantine',
        'cache' => $_ENV['CACHE_PATH'] ?? __DIR__ . '/../storage/cache',
        'logs' => $_ENV['LOG_PATH'] ?? __DIR__ . '/../storage/logs',
        'audit' => $_ENV['AUDIT_PATH'] ?? __DIR__ . '/../storage/audit',
        'backups' => $_ENV['BACKUP_PATH'] ?? __DIR__ . '/../storage/backups',
        'tokens' => $_ENV['TOKEN_STORE_FILE'] ?? __DIR__ . '/../storage/tokens/tokens.json',
    ],

    'audit' => [
        'enabled' => filter_var($_ENV['AUDIT_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'file' => $_ENV['AUDIT_FILE'] ?? ((__DIR__ . '/../storage/audit/security-audit.log')),
        'mirror_to_log' => filter_var($_ENV['AUDIT_MIRROR_TO_LOG'] ?? false, FILTER_VALIDATE_BOOL),
        'log_file' => $_ENV['AUDIT_LOG_FILE'] ?? ((__DIR__ . '/../storage/logs/security-audit.log')),
        'auto' => [
            // Enable to automatically log safe request outcomes for add/edit/delete/submission/email/auth routes.
            'enabled' => filter_var($_ENV['AUDIT_AUTO_ENABLED'] ?? false, FILTER_VALIDATE_BOOL),
            'log_reads' => filter_var($_ENV['AUDIT_AUTO_LOG_READS'] ?? false, FILTER_VALIDATE_BOOL),
            'log_preflight' => filter_var($_ENV['AUDIT_AUTO_LOG_PREFLIGHT'] ?? false, FILTER_VALIDATE_BOOL),
            'excluded_paths' => array_values(array_filter(array_map('trim', explode(',', $_ENV['AUDIT_AUTO_EXCLUDED_PATHS'] ?? 'health,healthz,metrics,favicon.ico')))),
            'sensitive_input_keys' => ['password', 'password_confirmation', 'current_password', 'new_password', 'token', 'api_token', 'secret', 'api_key', 'authorization', 'cookie', 'session', 'csrf', 'otp', 'private_key'],
        ],
    ],


    'logging' => [
        'enabled' => filter_var($_ENV['LOGGING_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'default_channel' => $_ENV['LOGGING_DEFAULT_CHANNEL'] ?? 'app',
        'redaction' => [
            'enabled' => filter_var($_ENV['LOGGING_REDACTION_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
            'use_secret_redactor' => true,
            'use_data_protection' => true,
        ],
        'channels' => [
            'app' => [
                'level' => $_ENV['LOG_LEVEL'] ?? 'info',
                'handler' => 'json_file',
                'path' => $_ENV['APP_LOG_FILE'] ?? (__DIR__ . '/../storage/logs/app.jsonl'),
            ],
            'security' => [
                'level' => $_ENV['SECURITY_LOG_LEVEL'] ?? 'warning',
                'handler' => 'json_file',
                'path' => $_ENV['SECURITY_LOG_FILE'] ?? (__DIR__ . '/../storage/logs/security.jsonl'),
            ],
            'audit' => [
                'level' => 'info',
                'handler' => 'json_file',
                'path' => $_ENV['AUDIT_MIRROR_LOG_FILE'] ?? (__DIR__ . '/../storage/logs/audit.jsonl'),
            ],
        ],
        'retention' => [
            'app_days' => (int)($_ENV['LOG_RETENTION_APP_DAYS'] ?? 14),
            'security_days' => (int)($_ENV['LOG_RETENTION_SECURITY_DAYS'] ?? 90),
            'audit_days' => (int)($_ENV['LOG_RETENTION_AUDIT_DAYS'] ?? 365),
            'debug_days' => (int)($_ENV['LOG_RETENTION_DEBUG_DAYS'] ?? 7),
        ],
    ],

    'monitoring' => [
        'enabled' => filter_var($_ENV['MONITORING_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'metrics' => [
            'enabled' => filter_var($_ENV['MONITORING_METRICS_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
            'driver' => $_ENV['MONITORING_METRICS_DRIVER'] ?? 'file',
            'path' => $_ENV['MONITORING_METRICS_FILE'] ?? (__DIR__ . '/../storage/logs/metrics.json'),
        ],
        'alerts' => [
            'enabled' => filter_var($_ENV['MONITORING_ALERTS_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
            'channels' => array_values(array_filter(array_map('trim', explode(',', $_ENV['MONITORING_ALERT_CHANNELS'] ?? 'file')))),
            'file' => $_ENV['MONITORING_ALERT_FILE'] ?? (__DIR__ . '/../storage/logs/security-alerts.jsonl'),
            'event_file' => $_ENV['MONITORING_EVENT_FILE'] ?? (__DIR__ . '/../storage/logs/monitoring-events.jsonl'),
            'webhook_url' => $_ENV['MONITORING_ALERT_WEBHOOK_URL'] ?? '',
            'rules' => [
                'failed_login_spike' => [
                    'event' => 'auth.login.failure',
                    'threshold' => (int)($_ENV['ALERT_FAILED_LOGIN_THRESHOLD'] ?? 10),
                    'window_seconds' => 300,
                    'severity' => 'high',
                ],
                'authorization_denial_spike' => [
                    'event' => 'authorization.access.denied',
                    'threshold' => (int)($_ENV['ALERT_AUTHZ_DENIAL_THRESHOLD'] ?? 20),
                    'window_seconds' => 600,
                    'severity' => 'high',
                ],
                'malware_upload_detected' => [
                    'event' => 'file.upload.rejected',
                    'threshold' => 1,
                    'window_seconds' => 60,
                    'severity' => 'critical',
                    'match' => ['context.reason' => 'malware'],
                ],
                'audit_chain_broken' => [
                    'event' => 'audit.integrity.failed',
                    'threshold' => 1,
                    'window_seconds' => 60,
                    'severity' => 'critical',
                ],
            ],
        ],
    ],


    'recovery' => [
        'enabled' => filter_var($_ENV['RECOVERY_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'backups' => [
            'enabled' => filter_var($_ENV['BACKUP_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
            'path' => $_ENV['BACKUP_PATH'] ?? (__DIR__ . '/../storage/backups'),
            'encrypt' => filter_var($_ENV['BACKUP_ENCRYPT'] ?? true, FILTER_VALIDATE_BOOL),
            'sign' => filter_var($_ENV['BACKUP_SIGN'] ?? true, FILTER_VALIDATE_BOOL),
            'key' => $_ENV['BACKUP_KEY'] ?? ($_ENV['APP_KEY'] ?? ''),
            'signing_key' => $_ENV['BACKUP_SIGNING_KEY'] ?? ($_ENV['APP_KEY'] ?? ''),
            'include' => [__DIR__],
            'exclude' => [__DIR__ . '/../vendor', __DIR__ . '/../.git', __DIR__ . '/../storage/cache', __DIR__ . '/../storage/logs'],
            'retention' => [
                'daily_days' => (int)($_ENV['BACKUP_RETENTION_DAILY_DAYS'] ?? 7),
                'weekly_weeks' => (int)($_ENV['BACKUP_RETENTION_WEEKLY_WEEKS'] ?? 4),
                'monthly_months' => (int)($_ENV['BACKUP_RETENTION_MONTHLY_MONTHS'] ?? 12),
            ],
        ],
        'restore' => [
            'allow_overwrite' => filter_var($_ENV['RESTORE_ALLOW_OVERWRITE'] ?? false, FILTER_VALIDATE_BOOL),
            'require_signature' => filter_var($_ENV['RESTORE_REQUIRE_SIGNATURE'] ?? true, FILTER_VALIDATE_BOOL),
            'require_encryption' => filter_var($_ENV['RESTORE_REQUIRE_ENCRYPTION'] ?? true, FILTER_VALIDATE_BOOL),
            'restore_to_temp_first' => true,
            'audit' => true,
        ],
        'drills' => [
            'enabled' => filter_var($_ENV['RECOVERY_DRILLS_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
            'last_success_max_age_days' => (int)($_ENV['RECOVERY_DRILL_MAX_AGE_DAYS'] ?? 30),
        ],
    ],

    'incident_response' => [
        'enabled' => filter_var($_ENV['INCIDENT_RESPONSE_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'file' => $_ENV['INCIDENT_FILE'] ?? (__DIR__ . '/../storage/logs/incidents.jsonl'),
        'default_severity' => $_ENV['INCIDENT_DEFAULT_SEVERITY'] ?? 'medium',
        'audit' => true,
        'collect_evidence' => true,
        'playbooks' => [
            'failed_login_spike' => [
                'severity' => 'high',
                'actions' => ['record_incident', 'invalidate_user_auth_cache', 'alert_security'],
            ],
            'malware_upload_detected' => [
                'severity' => 'critical',
                'actions' => ['record_incident', 'quarantine_file', 'deny_file_download', 'alert_security', 'collect_evidence'],
            ],
            'secret_leak_detected' => [
                'severity' => 'critical',
                'actions' => ['record_incident', 'rotate_secret_plan', 'revoke_tokens', 'invalidate_cache', 'collect_evidence', 'alert_security'],
            ],
            'audit_chain_broken' => [
                'severity' => 'critical',
                'actions' => ['record_incident', 'collect_evidence', 'alert_security', 'freeze_audit_export'],
            ],
        ],
    ],

    'limits' => [
        'request_max_bytes' => 12 * 1024 * 1024,
        'upload_max_bytes' => 10 * 1024 * 1024,
        'login' => ['max' => 5, 'seconds' => 600, 'key_by' => ['ip', 'route']],
        'api' => ['max' => 120, 'seconds' => 60, 'key_by' => ['ip', 'user', 'route']],
        'otp' => ['max' => 3, 'seconds' => 600, 'key_by' => ['ip', 'user', 'route']],
        'export' => ['max' => 10, 'seconds' => 3600, 'key_by' => ['user', 'route']],
    ],
    'uploads' => [
        // Built-in profiles: default, images, documents, videos, archives, strict.
        // Keep legacy allow-lists below for backward compatibility; set UPLOAD_PROFILE to use a preset.
        'profile' => $_ENV['UPLOAD_PROFILE'] ?? 'custom',
        'strict_production' => filter_var($_ENV['UPLOAD_STRICT_PRODUCTION'] ?? (($_ENV['APP_ENV'] ?? 'local') === 'production' ? true : false), FILTER_VALIDATE_BOOL),
        'allow_archives_in_production' => filter_var($_ENV['UPLOAD_ALLOW_ARCHIVES_IN_PRODUCTION'] ?? false, FILTER_VALIDATE_BOOL),
        'allowed_extensions' => ['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv'],
        'allowed_mime_prefixes' => ['image/', 'application/pdf', 'text/', 'application/vnd.', 'application/msword'],
        'blocked_extensions' => ['php', 'phtml', 'phar', 'cgi', 'pl', 'sh', 'exe', 'com', 'bat', 'cmd', 'js', 'html', 'htm', 'svg'],
        'deny_double_extensions' => true,
        'randomize_names' => true,
        'max_original_name_length' => 180,
        'reject_executable_content' => true,
        'max_archive_entries' => (int)($_ENV['UPLOAD_MAX_ARCHIVE_ENTRIES'] ?? 500),
        'max_archive_uncompressed_bytes' => (int)($_ENV['UPLOAD_MAX_ARCHIVE_UNCOMPRESSED_BYTES'] ?? 104857600),
        'profiles' => [
            'images' => ['max_bytes' => 5 * 1024 * 1024],
            'documents' => ['max_bytes' => 15 * 1024 * 1024],
            'videos' => ['max_bytes' => 100 * 1024 * 1024],
            'archives' => ['max_bytes' => 25 * 1024 * 1024],
            'strict' => ['max_bytes' => 5 * 1024 * 1024],
        ],
        'scanner' => [
            // none, heuristic, clamav, composite
            'driver' => $_ENV['UPLOAD_SCANNER_DRIVER'] ?? 'heuristic',
            'clamav_binary' => $_ENV['CLAMAV_BINARY'] ?? 'clamscan',
            'timeout_seconds' => (int)($_ENV['UPLOAD_SCAN_TIMEOUT'] ?? 30),
            'fail_closed' => filter_var($_ENV['UPLOAD_SCAN_FAIL_CLOSED'] ?? (($_ENV['APP_ENV'] ?? 'local') === 'production' ? true : false), FILTER_VALIDATE_BOOL),
            'heuristic_read_bytes' => (int)($_ENV['UPLOAD_HEURISTIC_READ_BYTES'] ?? 2097152),
        ],
    ],


    'runtime' => [
        'enabled' => filter_var($_ENV['RUNTIME_SECURITY_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'deny_by_default' => filter_var($_ENV['RUNTIME_DENY_BY_DEFAULT'] ?? true, FILTER_VALIDATE_BOOL),
        'default_timeout_seconds' => (int)($_ENV['RUNTIME_DEFAULT_TIMEOUT'] ?? 10),
        'max_output_bytes' => (int)($_ENV['RUNTIME_MAX_OUTPUT_BYTES'] ?? 65536),
        'allowed_env' => array_values(array_filter(array_map('trim', explode(',', $_ENV['RUNTIME_ALLOWED_ENV'] ?? 'PATH,TMPDIR,TEMP')))),
        'allowed_working_directories' => [
            __DIR__ . '/../storage/private',
            __DIR__ . '/../storage/quarantine',
        ],
        'commands' => [
            'clamav_scan' => [
                'binary' => $_ENV['CLAMAV_BINARY'] ?? 'clamscan',
                'allowed_args' => ['--no-summary', '--infected'],
                'timeout_seconds' => (int)($_ENV['UPLOAD_SCAN_TIMEOUT'] ?? 30),
                'max_output_bytes' => 65536,
            ],
        ],
    ],

    'network' => [
        'outbound' => [
            'enabled' => filter_var($_ENV['OUTBOUND_SECURITY_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
            'https_only' => filter_var($_ENV['OUTBOUND_HTTPS_ONLY'] ?? true, FILTER_VALIDATE_BOOL),
            'allowed_schemes' => array_values(array_filter(array_map('trim', explode(',', $_ENV['OUTBOUND_ALLOWED_SCHEMES'] ?? 'https')))),
            'allowed_hosts' => array_values(array_filter(array_map('trim', explode(',', $_ENV['OUTBOUND_ALLOWED_HOSTS'] ?? '')))),
            'blocked_hosts' => array_values(array_filter(array_map('trim', explode(',', $_ENV['OUTBOUND_BLOCKED_HOSTS'] ?? 'localhost,metadata.google.internal')))),
            'block_private_ips' => filter_var($_ENV['OUTBOUND_BLOCK_PRIVATE_IPS'] ?? true, FILTER_VALIDATE_BOOL),
            'block_loopback_ips' => filter_var($_ENV['OUTBOUND_BLOCK_LOOPBACK_IPS'] ?? true, FILTER_VALIDATE_BOOL),
            'block_link_local_ips' => filter_var($_ENV['OUTBOUND_BLOCK_LINK_LOCAL_IPS'] ?? true, FILTER_VALIDATE_BOOL),
            'block_metadata_ips' => filter_var($_ENV['OUTBOUND_BLOCK_METADATA_IPS'] ?? true, FILTER_VALIDATE_BOOL),
            'max_redirects' => (int)($_ENV['OUTBOUND_MAX_REDIRECTS'] ?? 3),
            'timeout_seconds' => (int)($_ENV['OUTBOUND_TIMEOUT_SECONDS'] ?? 5),
            'max_response_bytes' => (int)($_ENV['OUTBOUND_MAX_RESPONSE_BYTES'] ?? 1048576),
            'user_agent' => $_ENV['OUTBOUND_USER_AGENT'] ?? 'mnb-secure-core/1.0.1',
        ],
    ],

    'file_security' => [
        'enabled' => filter_var($_ENV['FILE_SECURITY_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'deny_by_default' => filter_var($_ENV['FILE_SECURITY_DENY_BY_DEFAULT'] ?? true, FILTER_VALIDATE_BOOL),
        'default_download_disposition' => $_ENV['FILE_DOWNLOAD_DISPOSITION'] ?? 'attachment',
        'deny_download_until_scan_passed' => filter_var($_ENV['FILE_DENY_DOWNLOAD_UNTIL_SCAN_PASSED'] ?? true, FILTER_VALIDATE_BOOL),
        'audit_downloads' => filter_var($_ENV['FILE_AUDIT_DOWNLOADS'] ?? true, FILTER_VALIDATE_BOOL),
        'audit_deletes' => filter_var($_ENV['FILE_AUDIT_DELETES'] ?? true, FILTER_VALIDATE_BOOL),
        'metadata' => [
            'require_owner' => filter_var($_ENV['FILE_REQUIRE_OWNER'] ?? false, FILTER_VALIDATE_BOOL),
            'require_tenant' => filter_var($_ENV['FILE_REQUIRE_TENANT'] ?? false, FILTER_VALIDATE_BOOL),
            'require_checksum' => filter_var($_ENV['FILE_REQUIRE_CHECKSUM'] ?? true, FILTER_VALIDATE_BOOL),
            'require_scan_status' => filter_var($_ENV['FILE_REQUIRE_SCAN_STATUS'] ?? true, FILTER_VALIDATE_BOOL),
        ],
        'download' => [
            'cache_policy' => 'download',
            'nosniff' => true,
            'safe_filename' => true,
            'allow_inline' => filter_var($_ENV['FILE_ALLOW_INLINE'] ?? false, FILTER_VALIDATE_BOOL),
            'inline_profiles' => ['images'],
            'signed_urls' => [
                'enabled' => filter_var($_ENV['FILE_SIGNED_URLS_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
                'ttl' => (int)($_ENV['FILE_SIGNED_URL_TTL'] ?? 900),
                'one_time' => false,
            ],
        ],
        'policies' => [
            'files.download' => [
                'actions' => ['download'],
                'roles' => [],
                'permissions' => [],
                'scopes' => [],
                'tenant_required' => false,
                'data_classes' => ['public', 'internal'],
                'require_scan_passed' => true,
                'disposition' => 'attachment',
                'allow_inline' => false,
                'inline_profiles' => ['images'],
                'cache_policy' => 'download',
                'audit' => true,
                'signed_urls' => ['enabled' => true, 'ttl' => 900],
            ],
            'student_document.download' => [
                'actions' => ['download'],
                'roles' => ['school_admin', 'teacher', 'super_admin'],
                'permissions' => ['documents.download'],
                'scopes' => ['documents:download'],
                'tenant_required' => true,
                'data_classes' => ['internal', 'confidential', 'sensitive'],
                'require_scan_passed' => true,
                'disposition' => 'attachment',
                'allow_inline' => false,
                'inline_profiles' => ['images'],
                'cache_policy' => 'download',
                'audit' => true,
                'signed_urls' => ['enabled' => true, 'ttl' => 900],
            ],
            'student_document.delete' => [
                'actions' => ['delete'],
                'roles' => ['school_admin', 'super_admin'],
                'permissions' => ['documents.delete'],
                'tenant_required' => true,
                'data_classes' => ['internal', 'confidential', 'sensitive'],
                'audit' => true,
            ],
        ],
        'inspection' => [
            'enabled' => true,
            'inspect_pdf' => true,
            'inspect_office' => true,
            'inspect_archives' => true,
            'max_nested_archive_depth' => 1,
        ],
        'sanitization' => [
            'enabled' => false,
            'driver' => 'null',
            'reencode_images' => false,
            'strip_image_metadata' => true,
            'strip_pdf_active_content' => false,
        ],
        'retention' => [
            'quarantine_ttl_hours' => 24,
            'rejected_ttl_days' => 7,
            'temporary_exports_ttl_hours' => 24,
        ],
    ],


    'cache' => [
        // file, redis, database
        'driver' => $_ENV['CACHE_DRIVER'] ?? 'file',
        'prefix' => $_ENV['CACHE_PREFIX'] ?? 'mnb:cache:',
        'table' => $_ENV['CACHE_TABLE'] ?? 'mnb_cache',
    ],

    'caching' => [
        'enabled' => filter_var($_ENV['CACHING_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'default_driver' => $_ENV['CACHE_DRIVER'] ?? 'file',
        'default_ttl' => (int)($_ENV['CACHE_DEFAULT_TTL'] ?? 300),
        'key_prefix' => $_ENV['CACHE_KEY_PREFIX'] ?? 'mnb',
        'tag_prefix' => $_ENV['CACHE_TAG_PREFIX'] ?? 'mnb:tag:',
        'security' => [
            'tenant_scoped_by_default' => filter_var($_ENV['CACHE_TENANT_SCOPED_BY_DEFAULT'] ?? true, FILTER_VALIDATE_BOOL),
            'user_scoped_for_sensitive' => filter_var($_ENV['CACHE_USER_SCOPED_FOR_SENSITIVE'] ?? true, FILTER_VALIDATE_BOOL),
            'deny_highly_sensitive' => filter_var($_ENV['CACHE_DENY_HIGHLY_SENSITIVE'] ?? true, FILTER_VALIDATE_BOOL),
            'encrypt_sensitive' => filter_var($_ENV['CACHE_ENCRYPT_SENSITIVE'] ?? true, FILTER_VALIDATE_BOOL),
            'max_value_bytes' => (int)($_ENV['CACHE_MAX_VALUE_BYTES'] ?? 1048576),
            'safe_serialization' => true,
        ],
        'stampede' => [
            'enabled' => filter_var($_ENV['CACHE_STAMPEDE_PROTECTION'] ?? true, FILTER_VALIDATE_BOOL),
            'lock_ttl' => (int)($_ENV['CACHE_LOCK_TTL'] ?? 15),
            'jitter_percent' => (int)($_ENV['CACHE_JITTER_PERCENT'] ?? 10),
            'stale_while_revalidate' => filter_var($_ENV['CACHE_STALE_WHILE_REVALIDATE'] ?? true, FILTER_VALIDATE_BOOL),
        ],
        'policies' => [
            'public_config' => [
                'ttl' => 3600,
                'data_class' => 'public',
                'scope' => ['global'],
                'tags' => ['config'],
            ],
            'school_settings' => [
                'ttl' => 600,
                'data_class' => 'internal',
                'scope' => ['tenant'],
                'tags' => ['school'],
            ],
            'student_profile' => [
                'ttl' => 300,
                'data_class' => 'sensitive',
                'scope' => ['tenant', 'user'],
                'encrypt' => true,
                'tags' => ['students'],
            ],
            'authz_decision' => [
                'ttl' => 120,
                'data_class' => 'confidential',
                'scope' => ['tenant', 'user'],
                'tags' => ['authz'],
            ],
            'highly_sensitive_default' => [
                'ttl' => 0,
                'data_class' => 'highly_sensitive',
                'cache' => false,
            ],
        ],
    ],
    'rate_limiter' => [
        // file, redis, database
        'driver' => $_ENV['RATE_LIMIT_DRIVER'] ?? 'file',
        'prefix' => $_ENV['RATE_LIMIT_PREFIX'] ?? 'mnb:rate:',
        'table' => $_ENV['RATE_LIMIT_TABLE'] ?? 'mnb_rate_limits',
    ],
    'token_store' => [
        // file, redis, database
        'driver' => $_ENV['TOKEN_STORE_DRIVER'] ?? 'file',
        'prefix' => $_ENV['TOKEN_STORE_PREFIX'] ?? 'mnb:token:',
        'table' => $_ENV['TOKEN_STORE_TABLE'] ?? 'mnb_api_tokens',
    ],
    'redis' => [
        'host' => $_ENV['REDIS_HOST'] ?? '127.0.0.1',
        'port' => (int)($_ENV['REDIS_PORT'] ?? 6379),
        'password' => $_ENV['REDIS_PASSWORD'] ?? null,
        'database' => isset($_ENV['REDIS_DATABASE']) ? (int)$_ENV['REDIS_DATABASE'] : null,
        'timeout' => (float)($_ENV['REDIS_TIMEOUT'] ?? 1.5),
    ],

    'cors' => [
        'enabled' => filter_var($_ENV['CORS_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'allowed_origins' => array_values(array_filter(array_map('trim', explode(',', $_ENV['CORS_ALLOWED_ORIGINS'] ?? 'http://localhost')))),
        'allowed_origin_patterns' => array_values(array_filter(array_map('trim', explode(',', $_ENV['CORS_ALLOWED_ORIGIN_PATTERNS'] ?? '')))),
        'allowed_methods' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
        'allowed_headers' => ['Content-Type', 'Authorization', 'X-CSRF-Token', 'X-Requested-With'],
        'exposed_headers' => ['X-Request-ID', 'X-RateLimit-Policy', 'X-RateLimit-Limit', 'X-RateLimit-Remaining', 'X-RateLimit-Reset'],
        'allow_credentials' => filter_var($_ENV['CORS_ALLOW_CREDENTIALS'] ?? false, FILTER_VALIDATE_BOOL),
        'allow_null_origin' => filter_var($_ENV['CORS_ALLOW_NULL_ORIGIN'] ?? false, FILTER_VALIDATE_BOOL),
        'allow_private_network' => filter_var($_ENV['CORS_ALLOW_PRIVATE_NETWORK'] ?? false, FILTER_VALIDATE_BOOL),
        'max_age' => (int)($_ENV['CORS_MAX_AGE'] ?? 600),
    ],
    'security_headers' => [
        'enabled' => filter_var($_ENV['SECURITY_HEADERS_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'hsts' => [
            'enabled' => filter_var($_ENV['HSTS_ENABLED'] ?? false, FILTER_VALIDATE_BOOL),
            'max_age' => (int)($_ENV['HSTS_MAX_AGE'] ?? 31536000),
            'include_subdomains' => filter_var($_ENV['HSTS_INCLUDE_SUBDOMAINS'] ?? true, FILTER_VALIDATE_BOOL),
            'preload' => filter_var($_ENV['HSTS_PRELOAD'] ?? false, FILTER_VALIDATE_BOOL),
            'only_on_https' => true,
        ],
        'csp' => [
            'enabled' => filter_var($_ENV['CSP_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
            'report_only' => filter_var($_ENV['CSP_REPORT_ONLY'] ?? false, FILTER_VALIDATE_BOOL),
            'nonce_enabled' => filter_var($_ENV['CSP_NONCE_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
            'auto_nonce' => filter_var($_ENV['CSP_AUTO_NONCE'] ?? false, FILTER_VALIDATE_BOOL),
            'nonce_directives' => ['script-src', 'style-src'],
            'directives' => [
                'default-src' => ["'self'"],
                'script-src' => ["'self'"],
                'style-src' => ["'self'"],
                'img-src' => ["'self'", 'data:'],
                'font-src' => ["'self'", 'data:'],
                'connect-src' => ["'self'"],
                'object-src' => ["'none'"],
                'base-uri' => ["'self'"],
                'form-action' => ["'self'"],
                'frame-ancestors' => ["'self'"],
            ],
        ],
        // Legacy frame_ancestors remains supported when custom csp.directives is not supplied.
        'frame_ancestors' => "'self'",
        'content_type_options' => 'nosniff',
        'referrer_policy' => 'strict-origin-when-cross-origin',
        'x_frame_options' => 'SAMEORIGIN',
        'permissions_policy' => [
            // strict, balanced, minimal, custom, none
            'preset' => $_ENV['PERMISSIONS_POLICY_PRESET'] ?? 'strict',
        ],
        'cross_origin_opener_policy' => $_ENV['CROSS_ORIGIN_OPENER_POLICY'] ?? 'same-origin',
        'cross_origin_resource_policy' => $_ENV['CROSS_ORIGIN_RESOURCE_POLICY'] ?? 'same-origin',
        'cross_origin_embedder_policy' => $_ENV['CROSS_ORIGIN_EMBEDDER_POLICY'] ?? null,
    ],


    'web_security' => [
        'enabled' => filter_var($_ENV['WEB_SECURITY_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'profiles' => [
            'browser_page' => [
                'security_headers' => true,
                'cache_policy' => 'private_user',
                'csrf' => false,
                'output_escape' => true,
            ],
            'browser_form' => [
                'security_headers' => true,
                'cache_policy' => 'sensitive_no_store',
                'csrf' => true,
                'input_validation' => true,
                'safe_redirects' => true,
                'output_escape' => true,
            ],
            'admin_panel' => [
                'security_headers' => true,
                'cache_policy' => 'sensitive_no_store',
                'csrf' => true,
                'auth_strategy' => 'admin_bearer',
                'authorization' => true,
                'frame_policy' => 'deny',
            ],
            'json_api' => [
                'security_headers' => true,
                'cors' => true,
                'cache_policy' => 'no_store',
                'input_validation' => true,
                'auth_strategy' => 'api_bearer',
                'authorization' => true,
            ],
            'upload_endpoint' => [
                'security_headers' => true,
                'cache_policy' => 'no_store',
                'csrf' => false,
                'auth_strategy' => 'api_bearer',
                'upload_profile' => 'documents',
            ],
        ],
        'redirects' => [
            'allow_external' => filter_var($_ENV['WEB_REDIRECT_ALLOW_EXTERNAL'] ?? false, FILTER_VALIDATE_BOOL),
            'allowed_hosts' => array_values(array_filter(array_map('trim', explode(',', $_ENV['WEB_REDIRECT_ALLOWED_HOSTS'] ?? '')))),
        ],
    
    'secrets' => [
        'enabled' => filter_var($_ENV['SECRETS_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'provider' => [
            // env, array. Cloud/Vault providers can implement SecretProviderInterface later.
            'driver' => $_ENV['SECRETS_DRIVER'] ?? 'env',
            'prefix' => $_ENV['SECRETS_PREFIX'] ?? '',
        ],
        'redaction' => [
            'enabled' => filter_var($_ENV['SECRETS_REDACTION_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
            'replacement' => $_ENV['SECRETS_REDACTION_REPLACEMENT'] ?? '[redacted]',
            'show_last' => (int)($_ENV['SECRETS_REDACTION_SHOW_LAST'] ?? 0),
            'redact_config_dumps' => true,
            'redact_audit_metadata' => true,
            'redact_error_context' => true,
        ],
        'derivation' => [
            'enabled' => filter_var($_ENV['SECRETS_DERIVATION_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
            'master' => $_ENV['SECRETS_DERIVATION_MASTER'] ?? 'APP_KEY',
            'salt' => $_ENV['APP_SECRET_SALT'] ?? 'mnb-secure-core',
        ],
        'definitions' => [
            'app.key' => [
                'env' => 'APP_KEY',
                'required' => true,
                'production_required' => true,
                'min_length' => 32,
                'purpose' => 'master application key',
                'rotatable' => true,
                'current_key_id' => $_ENV['APP_KEY_ID'] ?? 'app-v1',
                'created_at' => $_ENV['APP_KEY_CREATED_AT'] ?? null,
            ],
            'data.key' => [
                'env' => 'DATA_KEY',
                'required' => false,
                'derive_from' => 'app.key',
                'min_length' => 32,
                'purpose' => 'data encryption',
                'rotatable' => true,
                'current_key_id' => $_ENV['DATA_KEY_ID'] ?? 'data-v1',
                'created_at' => $_ENV['DATA_KEY_CREATED_AT'] ?? null,
            ],
            'data.search_hash_key' => [
                'env' => 'DATA_SEARCH_HASH_KEY',
                'required' => false,
                'derive_from' => 'app.key',
                'min_length' => 32,
                'purpose' => 'search hash / blind indexes',
                'rotatable' => true,
            ],
            'signed_url.key' => [
                'env' => 'SIGNED_URL_KEY',
                'required' => false,
                'derive_from' => 'app.key',
                'min_length' => 32,
                'purpose' => 'signed URL HMAC',
                'rotatable' => true,
            ],
            'webhook.secret' => [
                'env' => 'WEBHOOK_SECRET',
                'required' => false,
                'production_required' => false,
                'min_length' => 32,
                'purpose' => 'webhook HMAC verification',
                'rotatable' => true,
            ],
            'cache.encryption_key' => [
                'env' => 'CACHE_ENCRYPTION_KEY',
                'required' => false,
                'derive_from' => 'app.key',
                'min_length' => 32,
                'purpose' => 'sensitive cache encryption',
                'rotatable' => true,
            ],
            'backup.encryption_key' => [
                'env' => 'BACKUP_ENCRYPTION_KEY',
                'required' => false,
                'derive_from' => 'app.key',
                'min_length' => 32,
                'purpose' => 'backup encryption/signing',
                'rotatable' => true,
            ],
        ],
        'rotation' => [
            'warn_after_days' => (int)($_ENV['SECRETS_ROTATION_WARN_AFTER_DAYS'] ?? 180),
            'fail_after_days' => (int)($_ENV['SECRETS_ROTATION_FAIL_AFTER_DAYS'] ?? 365),
        ],
        'scanning' => [
            'enabled' => filter_var($_ENV['SECRETS_SCAN_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
            'entropy' => filter_var($_ENV['SECRETS_SCAN_ENTROPY'] ?? true, FILTER_VALIDATE_BOOL),
            'fail_on' => $_ENV['SECRETS_SCAN_FAIL_ON'] ?? 'high',
            'ignore_paths' => ['vendor/', 'storage/', '.git/', 'node_modules/'],
            'allow_patterns' => ['change-me', 'example', 'test-key', 'your-'],
        ],
    ],

    'cookies' => [
            'secure' => filter_var($_ENV['WEB_COOKIE_SECURE'] ?? (($_ENV['APP_ENV'] ?? 'local') === 'production'), FILTER_VALIDATE_BOOL),
            'http_only' => filter_var($_ENV['WEB_COOKIE_HTTP_ONLY'] ?? true, FILTER_VALIDATE_BOOL),
            'same_site' => $_ENV['WEB_COOKIE_SAME_SITE'] ?? 'Lax',
            'path' => '/',
        ],
        'cache' => [
            'profiles' => [],
        ],
        'html_sanitizer' => [
            'allowed_tags' => ['p', 'br', 'strong', 'em', 'ul', 'ol', 'li', 'a'],
            'allowed_attributes' => ['href', 'title'],
            'allow_data_images' => false,
        ],
        'signed_urls' => [
            'key' => $_ENV['SIGNED_URL_KEY'] ?? ($_ENV['APP_KEY'] ?? ''),
            'default_ttl' => (int)($_ENV['SIGNED_URL_TTL'] ?? 900),
        ],
    ],

    'request_validation' => [
        'enabled' => filter_var($_ENV['REQUEST_VALIDATION_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'sanitize' => filter_var($_ENV['REQUEST_SANITIZE_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'throw' => false,
        'error_status' => 422,
        'message' => 'Validation failed',
        'max_depth' => (int)($_ENV['REQUEST_VALIDATION_MAX_DEPTH'] ?? 10),
        'max_string_length' => (int)($_ENV['REQUEST_VALIDATION_MAX_STRING_LENGTH'] ?? 10000),
        'blocked_keys' => ['__proto__', 'prototype', 'constructor'],
        'default' => [
            'methods' => ['POST', 'PUT', 'PATCH'],
            'body' => [
                'sanitize' => true,
                'sanitize_rules' => ['*' => 'trim|strip_control_chars'],
            ],
            'query' => [
                'sanitize' => true,
                'sanitize_rules' => ['*' => 'trim|strip_control_chars'],
            ],
        ],
        // Define route-specific validation in applications:
        // 'routes' => [
        //     'register' => [
        //         'methods' => ['POST'],
        //         'path' => '/register',
        //         'body' => [
        //             'allowed_fields' => ['name', 'email', 'password'],
        //             'strict' => true,
        //             'sanitize_rules' => ['name' => 'trim|strip_tags|collapse_spaces|max_length:120', 'email' => 'trim|email'],
        //             'rules' => ['name' => 'required|string|min:2|max:120', 'email' => 'required|email|max:190', 'password' => 'required|string|min:8|max:128'],
        //         ],
        //     ],
        // ],
        'routes' => [],
    ],


    'authentication' => [
        'enabled' => filter_var($_ENV['AUTHENTICATION_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'defaults' => [
            'failure_message' => 'Authentication required',
            'audit' => true,
            'required' => true,
        ],
        'strategies' => [
            'api_bearer' => [
                'type' => 'bearer',
                'required' => true,
                'rate_policy' => 'api',
                'audit' => true,
            ],
            'optional_bearer' => [
                'type' => 'bearer',
                'required' => false,
                'audit' => false,
            ],
            'admin_bearer' => [
                'type' => 'bearer',
                'required' => true,
                'roles' => ['admin', 'super_admin'],
                'rate_policy' => 'api',
                'audit' => true,
            ],
            'web_session' => [
                'type' => 'session',
                'required' => true,
                'roles' => [],
                'audit' => true,
            ],
            'webhook_hmac' => [
                'type' => 'signature',
                'required' => true,
                'scopes' => ['webhook:receive'],
                'signature' => [
                    'signature_header' => $_ENV['WEBHOOK_SIGNATURE_HEADER'] ?? 'X-Signature',
                    'timestamp_header' => $_ENV['WEBHOOK_TIMESTAMP_HEADER'] ?? 'X-Timestamp',
                    'algorithm' => $_ENV['WEBHOOK_SIGNATURE_ALGORITHM'] ?? 'sha256',
                    'secret' => $_ENV['WEBHOOK_SECRET'] ?? '',
                    'tolerance_seconds' => (int)($_ENV['WEBHOOK_TIMESTAMP_TOLERANCE'] ?? 300),
                ],
                'audit' => true,
            ],
            'internal_system' => [
                'type' => 'bearer',
                'required' => true,
                'scopes' => ['system:*'],
                'roles' => ['system', 'internal_system'],
                'audit' => true,
            ],
        ],
        'password_policy' => [
            'min_length' => (int)($_ENV['PASSWORD_MIN_LENGTH'] ?? 12),
            'max_length' => (int)($_ENV['PASSWORD_MAX_LENGTH'] ?? 128),
            'require_mixed_case' => filter_var($_ENV['PASSWORD_REQUIRE_MIXED_CASE'] ?? false, FILTER_VALIDATE_BOOL),
            'require_number' => filter_var($_ENV['PASSWORD_REQUIRE_NUMBER'] ?? false, FILTER_VALIDATE_BOOL),
            'require_symbol' => filter_var($_ENV['PASSWORD_REQUIRE_SYMBOL'] ?? false, FILTER_VALIDATE_BOOL),
            'block_common_passwords' => filter_var($_ENV['PASSWORD_BLOCK_COMMON'] ?? true, FILTER_VALIDATE_BOOL),
            'block_user_context' => filter_var($_ENV['PASSWORD_BLOCK_USER_CONTEXT'] ?? true, FILTER_VALIDATE_BOOL),
        ],
        'login' => [
            'rate_policy' => 'login',
            'generic_failure_message' => 'Invalid credentials',
            'audit_failures' => true,
            'ttl_seconds' => (int)($_ENV['AUTH_TOKEN_TTL_SECONDS'] ?? 2592000),
        ],
    ],


    'authorization' => [
        'enabled' => filter_var($_ENV['AUTHORIZATION_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'deny_by_default' => filter_var($_ENV['AUTHORIZATION_DENY_BY_DEFAULT'] ?? true, FILTER_VALIDATE_BOOL),
        'audit_denials' => filter_var($_ENV['AUTHORIZATION_AUDIT_DENIALS'] ?? true, FILTER_VALIDATE_BOOL),
        'hide_denial_reasons' => filter_var($_ENV['AUTHORIZATION_HIDE_DENIAL_REASONS'] ?? true, FILTER_VALIDATE_BOOL),
        'policies' => [
            'public.read' => [
                'resource' => 'public_pages',
                'actions' => ['read'],
                'data_classes' => ['public'],
                'audit' => false,
                'fields' => [
                    'read' => ['*' => ['title', 'slug', 'body']],
                ],
            ],
            'students.read' => [
                'resource' => 'students',
                'actions' => ['read'],
                'roles' => ['school_admin', 'super_admin'],
                'permissions' => ['student.view'],
                'scopes' => ['students:read', 'student.view'],
                'tenant_required' => true,
                'data_classes' => ['internal', 'confidential', 'sensitive'],
                'trust_boundary' => 'students.read',
                'audit' => true,
                'fields' => [
                    'read' => [
                        'school_admin' => ['id', 'name', 'email', 'parent_phone', 'school_id', 'branch_id'],
                        'super_admin' => ['*'],
                    ],
                ],
            ],
            'students.update' => [
                'resource' => 'students',
                'actions' => ['update'],
                'roles' => ['school_admin', 'super_admin'],
                'permissions' => ['student.update'],
                'scopes' => ['students:update', 'student.update'],
                'tenant_required' => true,
                'data_classes' => ['sensitive'],
                'trust_boundary' => 'students.update',
                'audit' => true,
                'fields' => [
                    'write' => [
                        'school_admin' => ['name', 'email', 'parent_phone', 'branch_id'],
                        'super_admin' => ['*'],
                    ],
                ],
            ],
            'students.delete' => [
                'resource' => 'students',
                'actions' => ['delete'],
                'roles' => ['super_admin'],
                'permissions' => ['student.delete'],
                'scopes' => ['students:delete', 'student.delete'],
                'tenant_required' => true,
                'data_classes' => ['sensitive'],
                'trust_boundary' => 'students.delete',
                'audit' => true,
            ],
            'backup.run' => [
                'resource' => 'backups',
                'actions' => ['backup'],
                'roles' => ['internal_system', 'system'],
                'scopes' => ['system:backup', 'system:*'],
                'data_classes' => ['highly_sensitive'],
                'trust_boundary' => 'backup.run',
                'audit' => true,
            ],
        ],
    ],


    'data_protection' => [
        'enabled' => filter_var($_ENV['DATA_PROTECTION_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'default_class' => $_ENV['DATA_PROTECTION_DEFAULT_CLASS'] ?? 'internal',
        'deny_unclassified_fields' => filter_var($_ENV['DATA_PROTECTION_DENY_UNCLASSIFIED_FIELDS'] ?? false, FILTER_VALIDATE_BOOL),
        'audit' => filter_var($_ENV['DATA_PROTECTION_AUDIT'] ?? false, FILTER_VALIDATE_BOOL),
        'encryption' => [
            'enabled' => filter_var($_ENV['DATA_ENCRYPTION_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
            'current_key_id' => $_ENV['DATA_KEY_ID'] ?? 'app-v1',
            'keys' => [
                $_ENV['DATA_KEY_ID'] ?? 'app-v1' => $_ENV['DATA_KEY'] ?? ($_ENV['APP_KEY'] ?? ''),
            ],
            'aad' => filter_var($_ENV['DATA_ENCRYPTION_AAD'] ?? true, FILTER_VALIDATE_BOOL),
        ],
        'search_hash' => [
            'enabled' => filter_var($_ENV['DATA_SEARCH_HASH_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
            'key' => $_ENV['DATA_SEARCH_HASH_KEY'] ?? ($_ENV['APP_KEY'] ?? ''),
            'prefix' => $_ENV['DATA_SEARCH_HASH_PREFIX'] ?? 'mnb:search',
        ],
        'resources' => [
            'students' => [
                'default_class' => 'sensitive',
                'tenant_scoped' => true,
                'fields' => [
                    'id' => ['class' => 'internal'],
                    'name' => ['class' => 'internal'],
                    'email' => ['class' => 'confidential', 'encrypt' => true, 'search_hash' => true, 'mask' => 'email', 'export' => 'masked', 'log' => false],
                    'parent_phone' => ['class' => 'sensitive', 'encrypt' => true, 'search_hash' => true, 'mask' => 'last4', 'export' => 'masked', 'log' => false],
                    'school_id' => ['class' => 'internal'],
                    'branch_id' => ['class' => 'internal'],
                    'password_hash' => ['class' => 'highly_sensitive', 'read' => false, 'write' => false, 'export' => false, 'log' => false],
                ],
            ],
        ],
        'exports' => [
            'csv_injection_protection' => true,
            'audit' => true,
            'max_rows' => (int)($_ENV['DATA_EXPORT_MAX_ROWS'] ?? 50000),
        ],
        'storage' => [
            'encrypt_files' => filter_var($_ENV['DATA_ENCRYPT_FILES'] ?? false, FILTER_VALIDATE_BOOL),
        ],
        'backups' => [
            'encrypt' => filter_var($_ENV['DATA_BACKUP_ENCRYPT'] ?? false, FILTER_VALIDATE_BOOL),
            'sign' => filter_var($_ENV['DATA_BACKUP_SIGN'] ?? false, FILTER_VALIDATE_BOOL),
            'retention_days' => (int)($_ENV['DATA_BACKUP_RETENTION_DAYS'] ?? 30),
        ],
        'logs' => [
            'redact_before_write' => true,
        ],
    ],


    'request_receiving' => [
        'enabled' => filter_var($_ENV['REQUEST_RECEIVING_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'reject_body_on_get' => true,
        'blocked_methods' => ['TRACE', 'CONNECT'],
        'json_depth' => (int)($_ENV['REQUEST_JSON_DEPTH'] ?? 64),
        'json_max_bytes' => (int)($_ENV['REQUEST_JSON_MAX_BYTES'] ?? 1048576),
        'json_require_object' => true,
        'request_id' => [
            'header' => $_ENV['REQUEST_ID_HEADER'] ?? 'X-Request-ID',
            'accept_incoming' => filter_var($_ENV['REQUEST_ID_ACCEPT_INCOMING'] ?? true, FILTER_VALIDATE_BOOL),
            'max_length' => (int)($_ENV['REQUEST_ID_MAX_LENGTH'] ?? 80),
        ],
        'suspicious' => [
            // block or audit
            'mode' => $_ENV['SUSPICIOUS_REQUEST_MODE'] ?? 'block',
            'max_path_length' => (int)($_ENV['REQUEST_MAX_PATH_LENGTH'] ?? 2048),
            'max_parameters' => (int)($_ENV['REQUEST_MAX_PARAMETERS'] ?? 200),
        ],
        'webhook' => [
            'signature_header' => $_ENV['WEBHOOK_SIGNATURE_HEADER'] ?? 'X-Signature',
            'timestamp_header' => $_ENV['WEBHOOK_TIMESTAMP_HEADER'] ?? 'X-Timestamp',
            'algorithm' => $_ENV['WEBHOOK_SIGNATURE_ALGORITHM'] ?? 'sha256',
            'secret' => $_ENV['WEBHOOK_SECRET'] ?? '',
            'tolerance_seconds' => (int)($_ENV['WEBHOOK_TIMESTAMP_TOLERANCE'] ?? 300),
        ],
        'defaults' => [
            'request_id' => true,
            'request_trust' => true,
            'origin_protection' => true,
            'https' => true,
            'trusted_host' => true,
            'cors' => true,
            'security_headers' => true,
            'json_body' => true,
            'suspicious_detection' => true,
            'input_validation' => true,
            'auto_audit' => true,
        ],
        'profiles' => [
            'public_read' => [
                'methods' => ['GET', 'HEAD'],
                'max_bytes' => 65536,
                'content_types' => [],
                'rate_policy' => 'api',
                'auth' => null,
                'csrf' => false,
                'input_validation' => false,
                'auto_audit' => false,
            ],
            'public_form' => [
                'methods' => ['POST'],
                'max_bytes' => 1048576,
                'content_types' => ['application/x-www-form-urlencoded', 'multipart/form-data'],
                'rate_policy' => 'api',
                'auth' => null,
                'csrf' => true,
                'input_validation' => true,
                'auto_audit' => true,
            ],
            'api_public' => [
                'methods' => ['GET', 'POST'],
                'max_bytes' => 1048576,
                'content_types' => ['application/json'],
                'rate_policy' => 'api',
                'auth' => null,
                'csrf' => false,
                'input_validation' => true,
            ],
            'api_authenticated' => [
                'methods' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
                'max_bytes' => 1048576,
                'content_types' => ['application/json'],
                'rate_policy' => 'api',
                'auth' => 'bearer',
                'csrf' => false,
                'input_validation' => true,
                'trust_boundary' => null,
                'authorization' => null,
            ],
            'admin' => [
                'methods' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
                'max_bytes' => 1048576,
                'content_types' => ['application/json', 'application/x-www-form-urlencoded'],
                'rate_policy' => 'api',
                'auth' => 'bearer',
                'required_roles' => ['admin', 'super_admin'],
                'authorization' => 'students.read',
                'input_validation' => true,
                'auto_audit' => true,
            ],
            'upload_image' => [
                'methods' => ['POST'],
                'max_bytes' => 5242880,
                'content_types' => ['multipart/form-data'],
                'rate_policy' => 'api',
                'auth' => 'bearer',
                'upload_profile' => 'images',
                'input_validation' => true,
                'auto_audit' => true,
            ],
            'webhook' => [
                'methods' => ['POST'],
                'max_bytes' => 1048576,
                'content_types' => ['application/json'],
                'rate_policy' => 'api',
                'auth' => 'signature',
                'csrf' => false,
                'input_validation' => true,
                'auto_audit' => true,
            ],
            'internal_system' => [
                'methods' => ['POST'],
                'max_bytes' => 1048576,
                'content_types' => ['application/json'],
                'rate_policy' => 'api',
                'auth' => 'bearer',
                'trust_boundary' => 'backup.run',
                'input_validation' => true,
                'auto_audit' => true,
            ],
        ],
    ],


    'trust_boundaries' => [
        'enabled' => filter_var($_ENV['TRUST_BOUNDARIES_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'hide_denial_reasons' => filter_var($_ENV['TRUST_BOUNDARY_HIDE_DENIAL_REASONS'] ?? true, FILTER_VALIDATE_BOOL),
        'deny_unclassified_fields' => filter_var($_ENV['TRUST_BOUNDARY_DENY_UNCLASSIFIED_FIELDS'] ?? false, FILTER_VALIDATE_BOOL),
        'zones' => ['public', 'authenticated', 'school_admin', 'super_admin', 'internal_system'],
        'zone_data_access' => [
            'public' => ['public'],
            'authenticated' => ['public', 'internal'],
            'school_admin' => ['public', 'internal', 'confidential', 'sensitive'],
            'super_admin' => ['public', 'internal', 'confidential', 'sensitive'],
            'internal_system' => ['public', 'internal', 'confidential', 'sensitive', 'highly_sensitive'],
        ],
        'zone_resolvers' => [
            'school_admin' => ['roles' => ['school_admin', 'admin'], 'scopes' => ['school:*'], 'permissions' => ['school.manage', 'student.manage']],
            'super_admin' => ['roles' => ['super_admin', 'root', 'owner'], 'scopes' => ['admin:*', '*']],
            'internal_system' => ['roles' => ['internal_system', 'system'], 'scopes' => ['system:*', 'internal:*']],
        ],
        'resources' => [
            'students' => [
                'data_class' => 'sensitive',
                'tenant_scoped' => true,
                'fields' => [
                    'id' => 'internal',
                    'name' => 'internal',
                    'email' => 'confidential',
                    'parent_phone' => 'sensitive',
                    'school_id' => 'internal',
                    'branch_id' => 'internal',
                    'password_hash' => 'highly_sensitive',
                ],
            ],
            'public_pages' => [
                'data_class' => 'public',
                'tenant_scoped' => false,
                'fields' => ['title' => 'public', 'slug' => 'public', 'body' => 'public'],
            ],
        ],
        'rules' => [
            'public.read' => [
                'zones' => ['public', 'authenticated', 'school_admin', 'super_admin'],
                'data_classes' => ['public'],
                'actions' => ['read'],
                'resources' => ['public_pages'],
                'audit' => false,
            ],
            'students.read' => [
                'zones' => ['school_admin', 'super_admin'],
                'data_classes' => ['internal', 'confidential', 'sensitive'],
                'actions' => ['read'],
                'resources' => ['students'],
                'permissions' => ['student.view'],
                'tenant_required' => true,
                'audit' => true,
            ],
            'students.update' => [
                'zones' => ['school_admin', 'super_admin'],
                'data_classes' => ['sensitive'],
                'actions' => ['update'],
                'resources' => ['students'],
                'permissions' => ['student.update'],
                'tenant_required' => true,
                'audit' => true,
            ],
            'students.delete' => [
                'zones' => ['super_admin'],
                'data_classes' => ['sensitive'],
                'actions' => ['delete'],
                'resources' => ['students'],
                'permissions' => ['student.delete'],
                'tenant_required' => true,
                'audit' => true,
            ],
            'backup.run' => [
                'zones' => ['internal_system'],
                'data_classes' => ['highly_sensitive'],
                'actions' => ['backup'],
                'scopes' => ['system:backup', 'system:*'],
                'audit' => true,
            ],
        ],
    ],

    'vulnerability_matrix' => [
        'enabled' => filter_var($_ENV['VULNERABILITY_MATRIX_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'frameworks' => [
            'owasp_top_10_2021' => true,
            'cwe' => true,
        ],
        'reporting' => [
            'include_evidence' => true,
            'include_gaps' => true,
            'include_recommendations' => true,
            'minimum_passing_score' => (int)($_ENV['VULNERABILITY_MATRIX_MIN_SCORE'] ?? 80),
        ],
        'vulnerabilities' => [
            'sql_injection' => ['enabled' => true, 'severity' => 'critical'],
            'xss' => ['enabled' => true, 'severity' => 'high', 'expected_status' => 'partially_protected'],
            'csrf' => ['enabled' => true, 'severity' => 'high'],
            'broken_access_control' => ['enabled' => true, 'severity' => 'critical'],
            'sensitive_data_exposure' => ['enabled' => true, 'severity' => 'critical'],
            'secrets_exposure' => ['enabled' => true, 'severity' => 'critical'],
            'insecure_file_upload' => ['enabled' => true, 'severity' => 'critical'],
            'unsafe_file_download' => ['enabled' => true, 'severity' => 'high'],
            'ssrf' => ['enabled' => true, 'severity' => 'high', 'expected_status' => 'protected'],
            'command_injection' => ['enabled' => true, 'severity' => 'critical', 'expected_status' => 'protected'],
        ],
    ],


    'suggestions' => [
        'enabled' => filter_var($_ENV['SUGGESTIONS_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'max_results' => (int)($_ENV['SUGGESTIONS_MAX_RESULTS'] ?? 8),
        'rules' => [],
    ],

    'origin_protection' => [
        // This helps hide server/application identity. To truly hide the origin IP,
        // also use a CDN/reverse proxy and firewall the origin server.
        'enabled' => filter_var($_ENV['ORIGIN_PROTECTION_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'block_direct_ip_host' => filter_var($_ENV['BLOCK_DIRECT_IP_HOST'] ?? true, FILTER_VALIDATE_BOOL),
        'cdn_or_proxy_enabled' => filter_var($_ENV['CDN_OR_PROXY_ENABLED'] ?? false, FILTER_VALIDATE_BOOL),
        'require_cdn_or_proxy_in_production' => filter_var($_ENV['REQUIRE_CDN_OR_PROXY_IN_PRODUCTION'] ?? true, FILTER_VALIDATE_BOOL),
        // Reject spoofed Forwarded/X-Forwarded-* headers unless REMOTE_ADDR is trusted.
        'block_untrusted_forwarded_headers' => filter_var($_ENV['BLOCK_UNTRUSTED_FORWARDED_HEADERS'] ?? true, FILTER_VALIDATE_BOOL),
        // Enable only when every valid request reaches PHP through a configured trusted proxy/CDN.
        'require_trusted_proxy' => filter_var($_ENV['REQUIRE_TRUSTED_PROXY'] ?? false, FILTER_VALIDATE_BOOL),
        'strip_headers' => ['Server', 'X-Powered-By', 'X-AspNet-Version', 'X-AspNetMvc-Version', 'X-Generator', 'X-Runtime', 'X-Version'],
    ],


    'errors' => [
        'enabled' => true,
        'hide_frontend_errors' => true,
        'response_format' => getenv('ERROR_RESPONSE_FORMAT') ?: 'auto', // auto, json, html, text, problem_json
        'default_public_message' => 'Something went wrong. Please try again later.',
        'include_request_id' => true,
        'log_channel' => 'errors',
        'debug' => [
            'allow_in_production' => false,
            'include_stack_trace' => false,
            'include_file_line' => false,
            'max_stack_frames' => 8,
        ],
        'redaction' => [
            'enabled' => true,
            'redact_secrets' => true,
            'redact_paths' => true,
            'redact_pii' => true,
            'replacement' => '[redacted]',
        ],
        'validation' => [
            'normalize_field_names' => true,
            'hide_internal_fields' => true,
            'public_field_map' => [
                'password_hash' => 'password',
                'tenant_internal_id' => 'organization',
                'db_school_id' => 'school',
            ],
        ],
        'fingerprinting' => [
            'enabled' => true,
            'include_route' => true,
            'include_exception_class' => true,
            'include_error_code' => true,
        ],
        'escalation' => [
            'enabled' => true,
            'critical_error_threshold' => 5,
            'window_seconds' => 300,
            'alert_on_security_exception' => true,
            'alert_on_repeated_500' => true,
        ],
    ],


    'memory' => [
        'max_bytes' => 0, // 0 means use PHP memory_limit / unlimited when PHP is unlimited
        'warning_ratio' => (float)(getenv('MEMORY_WARNING_RATIO') ?: 0.75),
        'critical_ratio' => (float)(getenv('MEMORY_CRITICAL_RATIO') ?: 0.90),
        'default_chunk_size' => (int)(getenv('MEMORY_DEFAULT_CHUNK_SIZE') ?: 500),
        'min_chunk_size' => 25,
        'max_chunk_size' => (int)(getenv('MEMORY_MAX_CHUNK_SIZE') ?: 5000),
        'log_snapshots' => false,
        'guard_requests' => true,
    ],
    'database' => [
        'driver' => getenv('DB_DRIVER') ?: 'mysql',
        'host' => getenv('DB_HOST') ?: '127.0.0.1',
        'port' => getenv('DB_PORT') ?: '3306',
        'database' => getenv('DB_DATABASE') ?: '',
        'username' => getenv('DB_USERNAME') ?: '',
        'password' => getenv('DB_PASSWORD') ?: '',
        'charset' => getenv('DB_CHARSET') ?: 'utf8mb4',
        'require_policies' => true,
        'soft_delete_default' => true,
        'deny_raw_sql' => true,
        'audit_queries' => true,
        'audit_bindings' => false,
        'query_limits' => [
            'max_limit' => (int)(getenv('DB_QUERY_MAX_LIMIT') ?: 500),
            'default_limit' => (int)(getenv('DB_QUERY_DEFAULT_LIMIT') ?: 50),
            'max_offset' => (int)(getenv('DB_QUERY_MAX_OFFSET') ?: 10000),
            'max_search_length' => (int)(getenv('DB_QUERY_MAX_SEARCH_LENGTH') ?: 100),
            'max_filter_count' => (int)(getenv('DB_QUERY_MAX_FILTER_COUNT') ?: 20),
            'block_leading_wildcard' => filter_var(getenv('DB_BLOCK_LEADING_WILDCARD') ?: true, FILTER_VALIDATE_BOOL),
            'slow_query_ms' => (int)(getenv('DB_SLOW_QUERY_MS') ?: 750),
            'allowed_operators' => ['eq', 'neq', 'in', 'not_in', 'like', 'starts_with', 'ends_with', 'between', 'gte', 'lte', 'gt', 'lt', 'is_null', 'is_not_null'],
        ],
        'transactions' => [
            'enabled' => true,
            'max_operations' => (int)(getenv('DB_TRANSACTION_MAX_OPERATIONS') ?: 50),
            'audit_begin_commit_rollback' => true,
        ],
        'schema_changes' => [
            'enabled' => true,
            'require_super_admin' => true,
            'require_backup_before_alter' => true,
            'allow_destructive_changes' => false,
            'dry_run_default' => true,
            'allowed_operations' => ['add_column', 'add_index'],
        ],
        'field_protection' => [
            'enabled' => true,
            'mask_sensitive_columns' => true,
            'deny_password_columns' => true,
            'hidden_columns' => ['password', 'password_hash', 'remember_token', 'api_token', 'secret', 'private_key'],
            'masked_columns' => ['email', 'phone', 'mobile', 'mobile_number'],
        ],
    ],


    'throughput' => [
        'target_rps' => (float)(getenv('THROUGHPUT_TARGET_RPS') ?: 50),
        'warning_latency_ms' => (int)(getenv('THROUGHPUT_WARNING_LATENCY_MS') ?: 750),
        'critical_latency_ms' => (int)(getenv('THROUGHPUT_CRITICAL_LATENCY_MS') ?: 2000),
        'max_concurrency' => (int)(getenv('THROUGHPUT_MAX_CONCURRENCY') ?: 25),
        'queue_warning_depth' => (int)(getenv('THROUGHPUT_QUEUE_WARNING_DEPTH') ?: 1000),
        'sample_window_seconds' => (int)(getenv('THROUGHPUT_SAMPLE_WINDOW_SECONDS') ?: 60),
        'emit_headers' => true,
        'block_critical_latency' => false,
    ],

    'pentest' => [
        'enabled' => filter_var(getenv('PENTEST_ENABLED') ?: true, FILTER_VALIDATE_BOOL),
        'safe_mode' => true,
        'report_storage' => getenv('PENTEST_REPORT_PATH') ?: __DIR__ . '/../storage/logs',
        'evidence_storage' => getenv('PENTEST_EVIDENCE_PATH') ?: __DIR__ . '/../storage/audit/pentest',
        'redact_evidence' => true,
        'block_release_on_open_critical' => true,
        'block_release_on_open_high' => true,
        'accepted_risk_requires_approval' => true,
        'default_owner' => getenv('PENTEST_DEFAULT_OWNER') ?: 'security-owner',
        'default_scope' => ['web', 'api', 'database', 'files'],
        'required_profiles' => ['production_release', 'api_security', 'database_security'],
        'release_gate' => [
            'enabled' => true,
            'block_on_open_critical' => true,
            'block_on_open_high' => true,
            'allow_accepted_risk' => false,
            'require_retest_for_critical' => true,
            'require_retest_for_high' => true,
            'minimum_coverage_percent' => (int)(getenv('PENTEST_MIN_COVERAGE') ?: 90),
        ],
        'sla' => [
            'Critical' => 'P3D',
            'High' => 'P7D',
            'Medium' => 'P30D',
            'Low' => 'P90D',
            'Info' => null,
        ],
        'profiles' => [
            'production_release' => [
                'required_tests' => [
                    'PT-AUTH-001', 'PT-AUTHZ-001', 'PT-TENANT-001', 'PT-INJ-001',
                    'PT-XSS-001', 'PT-CSRF-001', 'PT-UPLOAD-001', 'PT-API-001',
                    'PT-DB-001', 'PT-RUNTIME-001', 'PT-SSRF-001', 'PT-ERR-001',
                ],
            ],
            'api_security' => [
                'required_tests' => ['PT-AUTH-001', 'PT-AUTHZ-001', 'PT-API-001', 'PT-SSRF-001', 'PT-ERR-001'],
            ],
            'database_security' => [
                'required_tests' => ['PT-INJ-001', 'PT-DB-001', 'PT-DB-002', 'PT-DB-003', 'PT-DB-004', 'PT-DB-005'],
            ],
        ],
    ],
];
