<?php
$base = require __DIR__ . '/security.php';

return array_replace_recursive($base, [
    'app' => [
        'env' => 'production',
        'debug' => false,
        'force_https' => true,
        'url' => $_ENV['APP_URL'] ?? 'https://example.com',
        'key' => $_ENV['APP_KEY'] ?? '',
        'trusted_hosts' => array_values(array_filter(array_map('trim', explode(',', $_ENV['TRUSTED_HOSTS'] ?? 'example.com')))),
        'trusted_proxies' => array_values(array_filter(array_map('trim', explode(',', $_ENV['TRUSTED_PROXIES'] ?? '')))),
    ],
    'cookies' => [
        'secure' => true,
        'http_only' => true,
        'same_site' => $_ENV['SESSION_SAME_SITE'] ?? 'Strict',
    ],
    'audit' => [
        'enabled' => true,
        'file' => $_ENV['AUDIT_FILE'] ?? 'storage/audit/security-audit.log',
        'mirror_to_log' => filter_var($_ENV['AUDIT_MIRROR_TO_LOG'] ?? false, FILTER_VALIDATE_BOOL),
        'log_file' => $_ENV['AUDIT_LOG_FILE'] ?? 'storage/logs/security-audit.log',
        'auto' => [
            'enabled' => filter_var($_ENV['AUDIT_AUTO_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
            'log_reads' => filter_var($_ENV['AUDIT_AUTO_LOG_READS'] ?? false, FILTER_VALIDATE_BOOL),
            'log_preflight' => false,
            'excluded_paths' => array_values(array_filter(array_map('trim', explode(',', $_ENV['AUDIT_AUTO_EXCLUDED_PATHS'] ?? 'health,healthz,metrics,favicon.ico')))),
            'sensitive_input_keys' => ['password', 'password_confirmation', 'current_password', 'new_password', 'token', 'api_token', 'secret', 'api_key', 'authorization', 'cookie', 'session', 'csrf', 'otp', 'private_key'],
        ],
    ],
    'cors' => [
        'enabled' => filter_var($_ENV['CORS_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'allowed_origins' => array_values(array_filter(array_map('trim', explode(',', $_ENV['CORS_ALLOWED_ORIGINS'] ?? ($_ENV['APP_URL'] ?? 'https://example.com'))))),
        'allowed_origin_patterns' => array_values(array_filter(array_map('trim', explode(',', $_ENV['CORS_ALLOWED_ORIGIN_PATTERNS'] ?? '')))),
        'allowed_methods' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
        'allowed_headers' => ['Content-Type', 'Authorization', 'X-CSRF-Token', 'X-Requested-With'],
        'exposed_headers' => ['X-Request-ID', 'X-RateLimit-Policy', 'X-RateLimit-Limit', 'X-RateLimit-Remaining', 'X-RateLimit-Reset'],
        'allow_credentials' => filter_var($_ENV['CORS_ALLOW_CREDENTIALS'] ?? false, FILTER_VALIDATE_BOOL),
        'allow_null_origin' => false,
        'allow_private_network' => filter_var($_ENV['CORS_ALLOW_PRIVATE_NETWORK'] ?? false, FILTER_VALIDATE_BOOL),
        'max_age' => (int)($_ENV['CORS_MAX_AGE'] ?? 600),
    ],
    'uploads' => [
        'profile' => $_ENV['UPLOAD_PROFILE'] ?? 'documents',
        'strict_production' => true,
        'allow_archives_in_production' => filter_var($_ENV['UPLOAD_ALLOW_ARCHIVES_IN_PRODUCTION'] ?? false, FILTER_VALIDATE_BOOL),
        'scanner' => [
            'driver' => $_ENV['UPLOAD_SCANNER_DRIVER'] ?? 'composite',
            'clamav_binary' => $_ENV['CLAMAV_BINARY'] ?? 'clamscan',
            'timeout_seconds' => (int)($_ENV['UPLOAD_SCAN_TIMEOUT'] ?? 30),
            'fail_closed' => true,
            'heuristic_read_bytes' => (int)($_ENV['UPLOAD_HEURISTIC_READ_BYTES'] ?? 2097152),
        ],
    ],
    'security_headers' => [
        'enabled' => true,
        'hsts' => [
            'enabled' => true,
            'max_age' => (int)($_ENV['HSTS_MAX_AGE'] ?? 31536000),
            'include_subdomains' => filter_var($_ENV['HSTS_INCLUDE_SUBDOMAINS'] ?? true, FILTER_VALIDATE_BOOL),
            'preload' => filter_var($_ENV['HSTS_PRELOAD'] ?? false, FILTER_VALIDATE_BOOL),
            'only_on_https' => true,
        ],
        'csp' => [
            'enabled' => true,
            'report_only' => filter_var($_ENV['CSP_REPORT_ONLY'] ?? false, FILTER_VALIDATE_BOOL),
            'nonce_enabled' => true,
            'auto_nonce' => true,
            'nonce_directives' => ['script-src', 'style-src'],
            'directives' => [
                'default-src' => ["'self'"],
                'script-src' => ["'self'"],
                'style-src' => ["'self'"],
                'img-src' => ["'self'", 'data:'],
                'font-src' => ["'self'", 'data:'],
                'connect-src' => ["'self'"],
                'object-src' => ["'none'"],
                'base-uri' => ["'self'"],
                'form-action' => ["'self'"],
                'frame-ancestors' => ["'self'"],
            ],
        ],
        'permissions_policy' => ['preset' => $_ENV['PERMISSIONS_POLICY_PRESET'] ?? 'strict'],
        'cross_origin_opener_policy' => $_ENV['CROSS_ORIGIN_OPENER_POLICY'] ?? 'same-origin',
        'cross_origin_resource_policy' => $_ENV['CROSS_ORIGIN_RESOURCE_POLICY'] ?? 'same-origin',
        'cross_origin_embedder_policy' => $_ENV['CROSS_ORIGIN_EMBEDDER_POLICY'] ?? null,
    ],

    'request_validation' => [
        'enabled' => filter_var($_ENV['REQUEST_VALIDATION_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'sanitize' => filter_var($_ENV['REQUEST_SANITIZE_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'throw' => false,
        'error_status' => 422,
        'message' => 'Validation failed',
        'max_depth' => (int)($_ENV['REQUEST_VALIDATION_MAX_DEPTH'] ?? 10),
        'max_string_length' => (int)($_ENV['REQUEST_VALIDATION_MAX_STRING_LENGTH'] ?? 10000),
        'blocked_keys' => ['__proto__', 'prototype', 'constructor'],
        'default' => [
            'methods' => ['POST', 'PUT', 'PATCH'],
            'body' => [
                'sanitize' => true,
                'sanitize_rules' => ['*' => 'trim|strip_control_chars'],
            ],
            'query' => [
                'sanitize' => true,
                'sanitize_rules' => ['*' => 'trim|strip_control_chars'],
            ],
        ],
        // Define route-specific validation in applications:
        // 'routes' => [
        //     'register' => [
        //         'methods' => ['POST'],
        //         'path' => '/register',
        //         'body' => [
        //             'allowed_fields' => ['name', 'email', 'password'],
        //             'strict' => true,
        //             'sanitize_rules' => ['name' => 'trim|strip_tags|collapse_spaces|max_length:120', 'email' => 'trim|email'],
        //             'rules' => ['name' => 'required|string|min:2|max:120', 'email' => 'required|email|max:190', 'password' => 'required|string|min:8|max:128'],
        //         ],
        //     ],
        // ],
        'routes' => [],
    ],


    'request_receiving' => [
        'enabled' => filter_var($_ENV['REQUEST_RECEIVING_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'reject_body_on_get' => true,
        'blocked_methods' => ['TRACE', 'CONNECT'],
        'json_depth' => (int)($_ENV['REQUEST_JSON_DEPTH'] ?? 64),
        'json_max_bytes' => (int)($_ENV['REQUEST_JSON_MAX_BYTES'] ?? 1048576),
        'json_require_object' => true,
        'request_id' => [
            'header' => $_ENV['REQUEST_ID_HEADER'] ?? 'X-Request-ID',
            'accept_incoming' => filter_var($_ENV['REQUEST_ID_ACCEPT_INCOMING'] ?? true, FILTER_VALIDATE_BOOL),
            'max_length' => (int)($_ENV['REQUEST_ID_MAX_LENGTH'] ?? 80),
        ],
        'suspicious' => [
            'mode' => $_ENV['SUSPICIOUS_REQUEST_MODE'] ?? 'block',
            'max_path_length' => (int)($_ENV['REQUEST_MAX_PATH_LENGTH'] ?? 2048),
            'max_parameters' => (int)($_ENV['REQUEST_MAX_PARAMETERS'] ?? 200),
        ],
        'webhook' => [
            'signature_header' => $_ENV['WEBHOOK_SIGNATURE_HEADER'] ?? 'X-Signature',
            'timestamp_header' => $_ENV['WEBHOOK_TIMESTAMP_HEADER'] ?? 'X-Timestamp',
            'algorithm' => $_ENV['WEBHOOK_SIGNATURE_ALGORITHM'] ?? 'sha256',
            'secret' => $_ENV['WEBHOOK_SECRET'] ?? '',
            'tolerance_seconds' => (int)($_ENV['WEBHOOK_TIMESTAMP_TOLERANCE'] ?? 300),
        ],
        'defaults' => [
            'request_id' => true,
            'request_trust' => true,
            'origin_protection' => true,
            'https' => true,
            'trusted_host' => true,
            'cors' => true,
            'security_headers' => true,
            'json_body' => true,
            'suspicious_detection' => true,
            'input_validation' => true,
            'auto_audit' => true,
        ],
        'profiles' => [
            'public_read' => ['methods' => ['GET', 'HEAD'], 'max_bytes' => 65536, 'content_types' => [], 'rate_policy' => 'api', 'auth' => null, 'input_validation' => false, 'auto_audit' => false],
            'public_form' => ['methods' => ['POST'], 'max_bytes' => 1048576, 'content_types' => ['application/x-www-form-urlencoded', 'multipart/form-data'], 'rate_policy' => 'api', 'auth' => null, 'csrf' => true, 'input_validation' => true, 'auto_audit' => true],
            'api_public' => ['methods' => ['GET', 'POST'], 'max_bytes' => 1048576, 'content_types' => ['application/json'], 'rate_policy' => 'api', 'auth' => null, 'input_validation' => true],
            'api_authenticated' => ['methods' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'], 'max_bytes' => 1048576, 'content_types' => ['application/json'], 'rate_policy' => 'api', 'auth' => 'bearer', 'input_validation' => true],
            'admin' => ['methods' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'], 'max_bytes' => 1048576, 'content_types' => ['application/json', 'application/x-www-form-urlencoded'], 'rate_policy' => 'api', 'auth' => 'bearer', 'required_roles' => ['admin', 'super_admin'], 'input_validation' => true, 'auto_audit' => true],
            'upload_image' => ['methods' => ['POST'], 'max_bytes' => 5242880, 'content_types' => ['multipart/form-data'], 'rate_policy' => 'api', 'auth' => 'bearer', 'upload_profile' => 'images', 'input_validation' => true, 'auto_audit' => true],
            'webhook' => ['methods' => ['POST'], 'max_bytes' => 1048576, 'content_types' => ['application/json'], 'rate_policy' => 'api', 'auth' => 'signature', 'csrf' => false, 'input_validation' => true, 'auto_audit' => true],
            'internal_system' => ['methods' => ['POST'], 'max_bytes' => 1048576, 'content_types' => ['application/json'], 'rate_policy' => 'api', 'auth' => 'bearer', 'trust_boundary' => 'backup.run', 'input_validation' => true, 'auto_audit' => true],
        ],
    ],


    'trust_boundaries' => [
        'enabled' => filter_var($_ENV['TRUST_BOUNDARIES_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'hide_denial_reasons' => filter_var($_ENV['TRUST_BOUNDARY_HIDE_DENIAL_REASONS'] ?? true, FILTER_VALIDATE_BOOL),
        'deny_unclassified_fields' => filter_var($_ENV['TRUST_BOUNDARY_DENY_UNCLASSIFIED_FIELDS'] ?? true, FILTER_VALIDATE_BOOL),
        'zones' => ['public', 'authenticated', 'school_admin', 'super_admin', 'internal_system'],
        'zone_data_access' => [
            'public' => ['public'],
            'authenticated' => ['public', 'internal'],
            'school_admin' => ['public', 'internal', 'confidential', 'sensitive'],
            'super_admin' => ['public', 'internal', 'confidential', 'sensitive'],
            'internal_system' => ['public', 'internal', 'confidential', 'sensitive', 'highly_sensitive'],
        ],
        'zone_resolvers' => [
            'school_admin' => ['roles' => ['school_admin', 'admin'], 'scopes' => ['school:*'], 'permissions' => ['school.manage', 'student.manage']],
            'super_admin' => ['roles' => ['super_admin', 'root', 'owner'], 'scopes' => ['admin:*', '*']],
            'internal_system' => ['roles' => ['internal_system', 'system'], 'scopes' => ['system:*', 'internal:*']],
        ],
        'resources' => [
            'students' => [
                'data_class' => 'sensitive',
                'tenant_scoped' => true,
                'fields' => [
                    'id' => 'internal',
                    'name' => 'internal',
                    'email' => 'confidential',
                    'parent_phone' => 'sensitive',
                    'school_id' => 'internal',
                    'branch_id' => 'internal',
                    'password_hash' => 'highly_sensitive',
                ],
            ],
            'public_pages' => [
                'data_class' => 'public',
                'tenant_scoped' => false,
                'fields' => ['title' => 'public', 'slug' => 'public', 'body' => 'public'],
            ],
        ],
        'rules' => [
            'public.read' => [
                'zones' => ['public', 'authenticated', 'school_admin', 'super_admin'],
                'data_classes' => ['public'],
                'actions' => ['read'],
                'resources' => ['public_pages'],
                'audit' => false,
            ],
            'students.read' => [
                'zones' => ['school_admin', 'super_admin'],
                'data_classes' => ['internal', 'confidential', 'sensitive'],
                'actions' => ['read'],
                'resources' => ['students'],
                'permissions' => ['student.view'],
                'tenant_required' => true,
                'audit' => true,
            ],
            'students.update' => [
                'zones' => ['school_admin', 'super_admin'],
                'data_classes' => ['sensitive'],
                'actions' => ['update'],
                'resources' => ['students'],
                'permissions' => ['student.update'],
                'tenant_required' => true,
                'audit' => true,
            ],
            'students.delete' => [
                'zones' => ['super_admin'],
                'data_classes' => ['sensitive'],
                'actions' => ['delete'],
                'resources' => ['students'],
                'permissions' => ['student.delete'],
                'tenant_required' => true,
                'audit' => true,
            ],
            'backup.run' => [
                'zones' => ['internal_system'],
                'data_classes' => ['highly_sensitive'],
                'actions' => ['backup'],
                'scopes' => ['system:backup', 'system:*'],
                'audit' => true,
            ],
        ],
    ],

    'suggestions' => [
        'enabled' => filter_var($_ENV['SUGGESTIONS_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'max_results' => (int)($_ENV['SUGGESTIONS_MAX_RESULTS'] ?? 8),
        'rules' => [],
    ],
    'origin_protection' => [
        'enabled' => true,
        'block_direct_ip_host' => true,
        'cdn_or_proxy_enabled' => filter_var($_ENV['CDN_OR_PROXY_ENABLED'] ?? true, FILTER_VALIDATE_BOOL),
        'require_cdn_or_proxy_in_production' => true,
        'block_untrusted_forwarded_headers' => true,
        'require_trusted_proxy' => filter_var($_ENV['REQUIRE_TRUSTED_PROXY'] ?? false, FILTER_VALIDATE_BOOL),
    ],
    'errors' => [
        'hide_frontend_errors' => true,
        'response_format' => $_ENV['ERROR_RESPONSE_FORMAT'] ?? 'auto',
        'default_public_message' => 'Something went wrong. Please try again later.',
        'include_request_id' => true,
        'log_channel' => 'errors',
    ],
]);
